# Generated by Django 4.2.2 on 2023-06-24 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_alter_response_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='accepted_response',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='response_accepted', to='news.response'),
        ),
    ]
